apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: climate-control
  namespace: {{ .Values.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: climate-control
  minReplicas: {{ .Values.climateControl.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.climateControl.autoscaling.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.climateControl.autoscaling.targetCPUUtilizationPercentage }}
