apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: fleet-ota
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    repoURL: https://github.com/kalbhor1124/fleet-ota.git
    targetRevision: main
    path: deploy/helm/fleet-ota
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: fleet-ota
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
